title: Site

columns:
  - width: 1/3
    sections:
      notes: sections/notes
      bookmarks: sections/bookmarks
      checkins: sections/checkins
      events: sections/events
      bookshelf: sections/bookshelf
      cvs: sections/cvs
      # albums: sections/albums

  - width: 1/3
    sections:
      articles: sections/articles
      rsvps: sections/rsvps
      replies: sections/replies
      likes: sections/likes
      reposts: sections/reposts

  - width: 1/3
    sections:
      pages:
        type: pages
        create: default
        #create: gallery # we want to create a new page with this template
        templates:
          - about
          - site-menu
          - home
          - default
          - speaking
          - gallery
